# Generated by Django 4.0.2 on 2023-06-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(max_length=255)),
                ('source_address', models.CharField(max_length=255)),
                ('destination_address', models.CharField(max_length=255)),
            ],
        ),
    ]
